### ISSUE TITLE
FR: Count person in door frame

### ISSUE THREAD

**Issue by noxhirsch** [Lyr3x/Roode#119]
**Is your feature request related to a problem? Please describe.**
When you use Roode to control the light, the light only comes on when you are already in the room - so you walk into the darkness.

**Describe the solution you'd like**
Here a config option "count_person_in_doorframe" or "count_presence_detection" would be handy, which also counts up if a person is only standing in the doorframe and nobody else is in the room.

**Describe alternatives you've considered**
This is my current workaround. The presence sensor needs an off-delay, because otherwise it can happen that after passing through the door the counter goes from 1 to 0 and back to 1. The off-delay must be on an extra sensor, so that the normal count process is not delayed.
The workaround works, but is IMHO relatively complicated for such an easy and useful feature and can probably be solved more efficiently internally in Roode.

```
binary_sensor:
  - platform: roode
    presence_sensor:
      name: $friendly_name presence
      id:  presence_sensor
      internal: true
  - platform: template
    id: presence_sensor_delay_off
    internal: true
    lambda: 'return id(presence_sensor).state;'
    filters:
      - delayed_off: 100ms
    on_state:
      then:
        - component.update: number_peoplecounter
      
number:
  - platform: roode
    people_counter:
      id: master_peoplecounter
      internal: true
      on_value:
        then:
          - component.update: number_peoplecounter
  - platform: template
    name: $friendly_name
    id: number_peoplecounter
    min_value: 0
    max_value: 1000
    icon: "mdi:counter"
    step: 1
    lambda: |-
      if(id(presence_sensor_delay_off).state && id(master_peoplecounter).state == 0) { return 1; } 
      else{ return id(master_peoplecounter).state; }
    set_action:
      then:
        - number.set:
            id: master_peoplecounter
            value: !lambda "return x;"
```

**Additional context**
