### ISSUE TITLE
Number of people more than 10

### ISSUE THREAD

**Issue by ipkamerebg** [Lyr3x/Roode#123]
Hi,

i have one issue, i have more than 10 people which need to be counted. How can i  change this number?
Thanks!:)

I am interested in your project, i have a need for people counting in several offices. Direct sunlight is killing me, because i have interferences, i have glass doors,sensor is in shade but anyhow there is a problem.
Please let me know if we could cooperate on this project, i am glad to sponsor  your effort.

**Comment by Lyr3x** [comment]
Sorry for the late reply: You can change the max number within the `people_counter` block like:
```
number:
  - platform: roode
    people_counter:
      id: peopleCounter
      name: $friendly_name people counter
      max_value: 12
```
