### ISSUE TITLE
Adjustable Counter Min-Max Limits

### ISSUE THREAD

**Issue by BEMSman** [Lyr3x/Roode#132]
Is it possible to be able to have adjustable minimum and maximum count endpoints?

An example would be instead of 0-10 it could be say -100 to +100.

Reasoning for above would be to allow calculating a count when there is more than one door into a space, i.e. when there is random entry / exit, you would use more than one unit and sum the counts externally.

**Comment by CarsonF** [comment]
Max is configurable currently.
```yaml
number:
  - platform: roode
    people_counter:
      max_value: 100
```

 I think min might be hardcoded to 0 but you could PR a change for that.
https://github.com/lyr3x/Roode/blob/master/components/roode/number.py#L31
