### ISSUE TITLE
Just tested v1.3.3

### ISSUE THREAD

**Issue by diplix** [Lyr3x/Roode#63]
i’ll just note what stuck out while testing it. not everything i conclude is meant as a feature request, it’s more a field report.

first off, my VL53L1X breakout board has an `xhut` pin, which needs to be set HIGH to work. i connected it to pin 23 and added the folowing yaml:
```
esphome:
  # ...
  on_boot:
    then:
      - output.turn_on: xshut

output:
  - platform: gpio
    pin: 23
    id: xshut
```
during my first tests, because of the missing xshut, roode "Failed to detect and initialize" the sensor and shut down because of a loop.
 https://github.com/Lyr3x/Roode/blob/d946b95c98a8048f7b0cb008d393a8c1ef50931a/components/roode/roode.cpp#L42

that’s kind of a pain, because it renders the esp32 useless and unable to over the air updates. logging the error and letting _esphome_ do it’s thing would be much nicer.

next problem i had was the watchdog. as long as the API was configured calling calibration caused a watchdog induced reboot. disabling initial calibration

```
roode:
  # ...
  calibration: false
```

enabled _esphome_ to run and loop, however there were constant API disconnections (every 1-2 seconds) . increasing the roode  `update_interval` to ~ 200ms or 400ms helped a little, but the API still disconnected eveery few seconds.

removing  the API entirely
```
#api:
#  password: !secret api_password
#  reboot_timeout: 60min
# ...
```

and unsing `mqtt:` helped: initial calibration ran through and an `update_interval` of 10ms was ok.

to substitute the API services, i configured mqtt subscribes:

```
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: !secret mqtt_port
  reboot_timeout: 20min
  
  on_message:
    - topic: ${devicename}/services/set_counter
      qos: 0
      then:
        - lambda: "id(roode_platform)->sendCounter(atoi(x.c_str()));"

    - topic: ${devicename}/services/reset_counter
      qos: 0
      then:
        - lambda: "id(roode_platform)->sendCounter(0);"

    - topic: ${devicename}/services/recalibrate
      qos: 0
      then:
        - lambda: "id(roode_platform)->recalibration();"
```

however calling `id(roode_platform)->recalibration();` while _roode_ is runing still calls the watchdog. setting and resetting the counter works fine this way.

since _esphome_ 2021.11 there is a feature called `entity_category` ([see esphome docs](https://esphome.io/components/sensor/index.html)). it would be nice to make the following `platform: roode` sensors "diagnostic": `distance_sensor`, `max_threshold_zone0`,`max_threshold_zone1`,`min_threshold_zone0`,`min_threshold_zone1`,`roi_height`, `roi_width` and `{"text_sensor":["platform":"roode", "version":[]]}`

other than that _roode_ works realy nice and reliably. i like how the auto-calibration works and the many diagnotic sensors for debugging and testing.

here are links to the parts i used:
* https://de.aliexpress.com/item/32957084608.html
* https://de.aliexpress.com/item/1005003056543472.html
