### ISSUE TITLE
Continuous distance readings

### ISSUE THREAD

**Issue by ruimarinho** [Lyr3x/Roode#72]
Hi @Lyr3x,

It seems like I've been able to enable just the `distance_sensor` in order to get continuous readings by disabling the people counter sensor.

Is this a supported use-case? I see that the distance changes a lot even if the sensor is completely stable, which might indicate the distance mode is not correctly configured. Should I be manually configuring the sensor to mode `2` (in my case)?

Thanks,

**Comment by Lyr3x** [comment]
Sure, it's possible to only use the readings. Remember that the calibration already sets a mode and timing budgets,which are fairly tight as we don't need super stable readings but rather quick one. Use the manual mode and set your own budget and you should be good to go!

**Comment by Lyr3x** [comment]
#73 Will fix the manual mode and you should configure something like this:
```
roode:
  id: roode_platform
  i2c_address: 0x29
  update_interval: 10ms
  manual:
    sensor_mode: 3
    roi_height: 16
    roi_width: 6
    manual_threshold: 1280 
    timing_budget: 50
  restore_values: false
```
