### ISSUE TITLE
Return the people count as a "sensor" instead of "number"

### ISSUE THREAD

**Issue by Seba-VT** [Lyr3x/Roode#89]
**Is your feature request related to a problem? Please describe.**
Currently, the output as a `number` displays the sliding bar when using it on lovelace.

**Describe the solution you'd like**
I would like to have the result of the counting as a `sensor` in order to display its value without the sliding bar on lovelace. 

**Describe alternatives you've considered**
Tried to create a new sensor that capture the value of the output but its format is not compatible.
```
number:
  - platform: roode
    people_counter:
      id: count
      name: $friendly_name people counter

 sensor:
   - platform: template
     id: people_in_lab
     name: "People in Lab"
     lambda: !lambda |-
       return id(count);
```
I get an error during compilation saying that it can't convert from `PersistedNumber` to `float`
